"""Add Instagram support and channel types

Revision ID: 7dffe0647e69
Revises: 
Create Date: 2025-10-11 01:26:51.712224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7dffe0647e69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('instagram_business_account_id', sa.String(length=255), nullable=True),
    sa.Column('page_id', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('app_id', sa.String(length=255), nullable=True),
    sa.Column('app_secret', sa.String(length=255), nullable=True),
    sa.Column('webhook_verify_token', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.Enum('email', 'instagram', 'facebook', 'whatsapp', name='channeltype'), nullable=False),
    sa.Column('post_id', sa.String(length=255), nullable=False),
    sa.Column('post_url', sa.String(length=500), nullable=True),
    sa.Column('post_text', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_media_posts_id'), 'social_media_posts', ['id'], unique=False)
    op.create_index(op.f('ix_social_media_posts_post_id'), 'social_media_posts', ['post_id'], unique=False)
    op.alter_column('ticket_messages', 'body',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=False)
    op.alter_column('ticket_messages', 'attachments_json',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.add_column('tickets', sa.Column('channel', sa.Enum('email', 'instagram', 'facebook', 'whatsapp', name='channeltype'), nullable=False))
    op.add_column('tickets', sa.Column('channel_identifier', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'channel_identifier')
    op.drop_column('tickets', 'channel')
    op.alter_column('ticket_messages', 'attachments_json',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('ticket_messages', 'body',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_social_media_posts_post_id'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_id'), table_name='social_media_posts')
    op.drop_table('social_media_posts')
    op.drop_table('instagram_config')
    # ### end Alembic commands ###
